name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Base Stats
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: output
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_theme: dark
          extras_css: |
            svg { background-color: #1a1b26 !important; }
            h1, h2, h3 { color: #2196F3 !important; }

      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: output
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_theme: dark
          extras_css: |
            svg { background-color: #1a1b26 !important; }
            h1, h2, h3 { color: #2196F3 !important; }

      - name: Top Languages
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: output
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          config_theme: dark
          extras_css: |
            svg { background-color: #1a1b26 !important; }
            h1, h2, h3 { color: #2196F3 !important; }
